### ISSUE TITLE
Variables, opérateurs et flux d'entrée/sortie

### ISSUE THREAD

**Issue by David-Moisan** [yoanbernabeu/Roadmap-Dev-Symfony#28]
- Les Types de variables
- Opérateurs
- Flux d'entrée/sortie

**Comment by yoanbernabeu** [comment]
Tu classerais cela dans quelle section @David-Moisan  ?
"Les bases de php" ?

Sans toi libre d'y affecter un label :)

**Comment by David-Moisan** [comment]
@yoanbernabeu j'ai essayé de labelisé mais je ne peux pas 😕 sinon je pense que ça irait dans algorithme

**Comment by yoanbernabeu** [comment]
C'est fait 👌
