### ISSUE TITLE
Logique booléenne et structures conditionnelles

### ISSUE THREAD

**Issue by David-Moisan** [yoanbernabeu/Roadmap-Dev-Symfony#29]
- Opérateurs booléens 
- Comparaisons 
- Tests (if else, switch)
- Condition ternaire

**Comment by yoanbernabeu** [comment]
Très bonne idée, il y a à mon avis tout un chapitre sur l'algorithmie (j'ai créé un label pour regrouper les issues sur le sujet).
Merci !

**Comment by David-Moisan** [comment]
Merci à toi pour ce projet ! En effet, l'algorithmie manque souvent dans le paysage formation/tuto sur YouTube ou autres.
