### ISSUE TITLE
Le paradigme MVC

### ISSUE THREAD

**Issue by David-Moisan** [yoanbernabeu/Roadmap-Dev-Symfony#32]
- Modèle (Entity.php)
- Vue (base.html.twig)
- Contrôleur (Controller.php)

**Comment by David-Moisan** [comment]
@yoanbernabeu  toujours pas accès aux labels :( je pensai le mettre dans les bases de Symfony

**Comment by yoanbernabeu** [comment]
> @yoanbernabeu toujours pas accès aux labels :( je pensai le mettre dans les bases de Symfony
Je sais même pas si je peux autoriser l'utilisation des labels, je vais regarder :)

Merci !

**Comment by David-Moisan** [comment]
Suite à la dernière PR on peut fermer cette issue
