### ISSUE TITLE
Intégration Algolia

### ISSUE THREAD

**Issue by yoanbernabeu** [yoanbernabeu/Roadmap-Dev-Symfony#50]
Mise en place d'un moteur de recherche avec. Algolia

**Comment by 94noni** [comment]
Tu pourrais regarder côté Meilisearch également :)

**Comment by yoanbernabeu** [comment]
> Tu pourrais regarder côté Meilisearch également :)

J'avoue, que pour me simplifier la vie, vu que "out of box" Docusaurus propose une intégration de Algolia je vais faire au plus simple :)

-> https://docusaurus.io/fr/docs/search

**Comment by yoanbernabeu** [comment]
Ajout du champ de recherche et création du compte chez Algolia.
(En attente d'une indexation, je pense... à suivre)

**Comment by yoanbernabeu** [comment]
Le mail de Algolia :
> Hi there,
Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

Wait & see :)
