### ISSUE TITLE
FAQ ficher readme

### ISSUE THREAD

**Issue by archistico** [yoanbernabeu/Roadmap-Dev-Symfony#90]
Petite question parce que je suis nulle en git

Après avoir fait le fork, pour syncroniser mon git avec les modifications faites sur ton depot: ce sont ces passages a faire?
```
// Setup
git remote add upstream https://github.com/yoanbernabeu/Roadmap-Dev-Symfony.git
git remote -v

// Recupération
git fetch upstream

// Maintenant nous avons la branche upstream en local, upstream/main
git branch -va

// Fusionnement
git checkout main
git merge upstream/main
```
C'est correct?

**Comment by yoanbernabeu** [comment]
> Petite question parce que je suis nulle en git
> 
> Après avoir fait le fork, pour syncroniser mon git avec les modifications faites sur ton depot: ce sont ces passages a faire?
> 
> ```
> // Setup
> git remote add upstream https://github.com/yoanbernabeu/Roadmap-Dev-Symfony.git
> git remote -v
> 
> // Recupération
> git fetch upstream
> 
> // Maintenant nous avons la branche upstream en local, upstream/main
> git branch -va
> 
> // Fusionnement
> git checkout main
> git merge upstream/main
> ```
> 
> C'est correct?

Je pense que cette documentation devrait répondre à ta question : [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
